Adds support for cloud-init options when creating vms
meffie/molecule-proxmox pull request #9
Opened 2023-03-24 14:59 UTC by riwar

I have added a task to configure that updates a VM with some optional cloud-init options. (Everything except cicustom, at this stage)

This will solve #8 and i guess it could be expanded upon to also fix #7

2023-03-31 13:02 UTC, meffie commented
Nice! Thank you.  (Sorry for the delay, I'll take a look today.)

2023-04-11 02:25 UTC, meffie requested changes
Thank you for the patch!  Just some minor changes requested if you have time.

It would be nice to add some text to the readme that mentions what needs to be done to have a cloud-init enabled template. I was able to get one to work by added a "cloud-init" drive in the proxmox web interface, and then installing cloud-init in the image (apt install cloud-init), then converting the template to an image.

Also, it would be helpful to have a test case in tests/proxmox_driver/molecule

Many thanks!

2023-04-11 02:25 UTC, meffie commented on README.rst
> +       template_ciopts:
I feel we do not really need the "template_ciopts" key. Looking at other drivers (like the vagrant driver), the options are at the same level as "name". That is this could be:
    platforms:
       - name: test01
         user: some_user
         password: some_password
         ...

2023-04-11 02:25 UTC, meffie commented on README.rst
> +
Nit: github does not show it, but there is trailing whitespace here, which should be removed before we merge. (Whitespace errors make diffs harder in the future)

2023-04-11 02:25 UTC, meffie commented on src/molecule_proxmox/playbooks/create.yml
> +      when: p.proxmox_template_ciopts is defined or p.template_ciopts.ipconfig is defined
We can remove the when condition of we remove the template_ciopts key. I think it is ok to run the update even if nothing changes.

2023-04-11 02:25 UTC, meffie commented on src/molecule_proxmox/playbooks/create.yml
> +        name: "{{ p.name }}"
It is important to us the vmid from the proxmox_clone variable returned (registered) from the clone task. Otherwise this task will sometimes randomly fail with the error message:

    failed: [localhost] (item=m01) => {"ansible_loop_var": "p", "changed": false, "msg": "Unable to update vm m01 with vmid None=int() argument must be a string, a bytes-like object or a number, not 'NoneType'", "p": {"name": "m01"}, "vmid": null}

I'll add more info on line 55 below.

2023-04-11 02:25 UTC, meffie commented on src/molecule_proxmox/playbooks/create.yml
> +        ciuser: "{{ p.proxmox_template_ciopts.ciuser | d(p.template_ciopts.ciuser, true) | d(omit, true) }}"
I know I had multiple names for the template name, but that was not great. I think for new options, we can
keep it simple. Maybe something like

        ciuser: "{{ rc.p.user | d(omit, true) }}"
        cipassword: "{{ rc.p.password | d(omit, true) }}"
        citype: "{{ rc.p.citype | d(omit, true) }}"
        ipconfig: "{{ rc.p.ipconfig | d(omit, true) }}"
        nameservers: "{{ rc.p.nameservers | d(omit, true) }}"
        searchdomains: "{{ rc.p.searchdomains | d(omit, true) }}"
        sshkeys: "{{ rc.p.sshkeys | d(omit, true) }}"

2023-04-11 02:25 UTC, meffie commented on src/molecule_proxmox/playbooks/create.yml
> +      loop: "{{ molecule_yml.platforms }}"
We need to use the 'proxmox_clone' variable here, which contains the results of the clone task, and fortunately contains the platforms list from the molecule_yml, in the 'p' key.   This is needed since there is a race condition after the clone, and the p.name can not be used yet. So this should look like the start task below:

          loop: "{{ proxmox_clone.results }}"
          loop_control:
            loop_var: rc
            label: "{{ rc.p.name, rc.vmid }}"

2023-04-11 02:25 UTC, meffie commented on src/molecule_proxmox/playbooks/create.yml
> +    - name: "Update molecule instance config(s)"
Do we really need to use this second task to update the image after the clone? It is not possible to just set the cloud-init data in the task above that does the "clone" operation?  I tried it, but it seems the cloud-init data was not set. It's not clear to me from the proxmox_kvm docs.

2023-04-17 19:13 UTC, meffie commented
Since I took too long to review this, I will just merge this change to the master branch, then merge changes based on my comments.

2023-04-17 19:14 UTC, meffie approved these changes
I will do a separate change to fix the issues mentioned.

2023-04-17 19:14 UTC, merged

2023-04-20 06:55 UTC, riwar commented
Hi, thanks for merging the code, and thanks for the comments :) 

I can try and se if get som time to write what is needed to get this working in proxmox, should i put this in the regular README.md, or would it be better to put it in it's own file, and link to it from the main readme?

And will look in to writing a test for this as well.

2023-04-20 12:20 UTC, meffie commented
Thanks @riwar

I've added a basic test case, so don't worry about adding a test. But of course more tests are always welcome if you have time.

I've added a line the the readme, but some more text and pointers may be helpful.  I was able to create a cloud-init disk using the proxmox gui after some guessing. Maybe we can just point to the proxmox documents online.